### ISSUE TITLE
Format variables with lowercase and underscores

### ISSUE THREAD

**Issue by jbogarin** [leon-domingo/mydict#1]
Hi,

I’ve been using the library for a project and it works great. Really a timesaver. One thing that I would like to see if it can be included as a feature is the ability to ask the library to get the json variables and change them from the mixedCase in the json to lowercase with underscores which is more normal in python.

For example, I get from the json taskId, and I would like to access it in python as task_id.

I can work on the pull request if you think this feature makes sense.

Best regards,

**Comment by leon-domingo** [comment]
Hi @jbogarin 
Firstable, my sincere apologies for the missing response on this. I think I never received a notification about this (or I did). I don't know. Sorry.

I think your idea might be useful, but can you tell me more about how can we manage this? Because maybe you want to get the snake_case version of a field, or not. I mean, it's a different functioning from the current implementation.

You're talking about **JSON** (don't know if it's because your getting your data from JSON), maybe a new param in **from_json** static method?
```
json_data = '{"myFoo": "bar"}'

@staticmethod
def from_json(json_source, case_type=None):
     ...

md = MyDict.from_json(json_data, case_type=MyDict.SNAKE_CASE)
# m.my_foo = 'bar'

md = MyDict.from_json(json_data, case_type=MyDict.CAMEL_CASE)
# m.myFoo = 'bar'

md = MyDict.from_json(json_data, case_type=MyDict.PASCAL_CASE)
# m.MyFoo = 'bar'

# maybe not that useful...
md = MyDict.from_json(json_data, case_type=MyDict.KEBAB_CASE)
# m['my-foo'] = 'bar'
```

and probably the counterpart in **to_json**:
```
md = MyDict(my_foo='bar')
json_data = md.to_json(case_type=MyDict.CAMEL_CASE)
# json_data = '{"myFoo": "bar"}'
```

Of course, any PR is welcomed!

**Comment by leon-domingo** [comment]
Resolved
https://github.com/leon-domingo/mydict/pull/6
